name: best_player
description: Best Player - Modern IPTV, VOD, and Live TV Player for Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vlc_player_16kb: ^7.4.2
  video_player: ^2.11.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  intl: ^0.19.0
  wakelock_plus: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
